openapi: 3.0.0
info:
  title: Curug API Spec
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Login
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_auth_login_yml
      description: ''
      tags:
        - Auth
      responses:
        '200':
          description: ''
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/login'
      servers:
        - url: http://127.0.0.1:8000
  /api/register:
    get:
      summary: Register
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_auth_register_yml
      description: ''
      tags:
        - Auth
      responses:
        '200':
          description: ''
      servers:
        - url: http://127.0.0.1:8000
  /api/master-field-sura:
    post:
      summary: create mastr field surat
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_master_field_surat_create_mastr_field_surat_yml
      description: ''
      tags:
        - Master Field Surat
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/create_mastr_field_surat'
      servers:
        - url: http://127.0.0.1:8000
  /api/kk:
    post:
      summary: Create KK
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_kk_create_kk_yml
      description: ''
      tags:
        - KK
      responses:
        '200':
          description: ''
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/create_kk'
      servers:
        - url: http://127.0.0.1:8000
  /api/penduduk/:
    post:
      summary: Create
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_penduduk_create_yml
      description: ''
      tags:
        - Penduduk
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      nik:
                        type: string
                      nama_lengkap:
                        type: string
                      kk_id:
                        type: integer
                      nama_ayah_kandung:
                        type: string
                      nama_ibu_kandung:
                        type: string
                      jenis_kelamin:
                        type: string
                      tanggal_lahir:
                        type: string
                      tempat_lahir:
                        type: string
                      agama:
                        type: string
                      pekerjaan:
                        type: string
                      status_perkawinan:
                        type: string
                      kewarganegaraan:
                        type: string
                      golongan_darah:
                        type: string
                      no_hp:
                        type: string
                      email:
                        type: string
                      status_hidup:
                        type: string
                      tanggal_meninggal:
                        type: string
                        nullable: true
                      alamat_id:
                        type: integer
                      pendidikan_id:
                        type: integer
                      alamat:
                        type: object
                        properties:
                          id:
                            type: integer
                          label_alamat:
                            type: string
                          is_utama:
                            type: integer
                          alamat_lengkap:
                            type: string
                          jalan:
                            type: string
                          gedung_perumahan:
                            type: string
                          nomor_rumah:
                            type: string
                          blok:
                            type: string
                          no_lantai:
                            type: string
                          no_unit:
                            type: string
                          rt:
                            type: string
                          rw:
                            type: string
                          desa:
                            type: string
                          dusun:
                            type: string
                          kecamatan:
                            type: string
                          kabupaten:
                            type: string
                          provinsi:
                            type: string
                          negara:
                            type: string
                          kode_pos:
                            type: string
                          patokan:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                      pendidikan:
                        type: object
                        properties:
                          id:
                            type: integer
                          tingkat_pendidikan:
                            type: string
                      kk:
                        type: object
                        properties:
                          id:
                            type: integer
                          no_kk:
                            type: string
                          nik_kepala_keluarga:
                            type: string
              example:
                success: true
                message: Data penduduk berhasil ditambahkan.
                data:
                  id: 140
                  nik: '33060242343243545126'
                  nama_lengkap: SITI MUBAIDAH MM
                  kk_id: 23
                  nama_ayah_kandung: SITI CHIPTIYAH MM
                  nama_ibu_kandung: MARGO UTOMO UTOMO
                  jenis_kelamin: Perempuan
                  tanggal_lahir: '1971-01-01T00:00:00.000000Z'
                  tempat_lahir: Purworejo
                  agama: Islam
                  pekerjaan: Petani/Pekebun
                  status_perkawinan: Belum Kawin
                  kewarganegaraan: Indonesia
                  golongan_darah: B
                  no_hp: '081904703153'
                  email: example@example.com
                  status_hidup: HIDUP
                  tanggal_meninggal: null
                  alamat_id: 18
                  pendidikan_id: 5
                  alamat:
                    id: 18
                    label_alamat: Rumah
                    is_utama: 1
                    alamat_lengkap: >-
                      Desa Curug, RT 001 RW 001, Kecamatan Ngombol, Kabupaten
                      Purworejo, Jawa Tengah.
                    jalan: Jln.Lingkar Barat
                    gedung_perumahan: Perum mawar
                    nomor_rumah: '338'
                    blok: '4'
                    no_lantai: '5'
                    no_unit: '6'
                    rt: '2'
                    rw: '2'
                    desa: Curug
                    dusun: Cagar
                    kecamatan: Ngombol
                    kabupaten: Purworejo
                    provinsi: Jawa Tengah
                    negara: Indonesia
                    kode_pos: '54172'
                    patokan: Belakang Puskesmas Ngombol
                    latitude: '-7.7839810'
                    longitude: '109.9614240'
                  pendidikan:
                    id: 5
                    tingkat_pendidikan: SLTA/Sederajat
                  kk:
                    id: 23
                    no_kk: '3306021308080442'
                    nik_kepala_keluarga: '3306020505680007'
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/create'
      servers:
        - url: http://127.0.0.1:8000
    delete:
      summary: Delete by ID
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_penduduk_delete_by_id_yml
      description: ''
      tags:
        - Penduduk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: string
                    nullable: true
              example:
                success: true
                message: Data berhasil dihapus.
                data: null
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
    get:
      summary: Get by ID
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_penduduk_get_by_id_yml
      description: ''
      tags:
        - Penduduk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      nik:
                        type: string
                      nama_lengkap:
                        type: string
                      kk_id:
                        type: integer
                      nama_ayah_kandung:
                        type: string
                      nama_ibu_kandung:
                        type: string
                      jenis_kelamin:
                        type: string
                      tanggal_lahir:
                        type: string
                      tempat_lahir:
                        type: string
                      agama:
                        type: string
                      pekerjaan:
                        type: string
                      status_perkawinan:
                        type: string
                      kewarganegaraan:
                        type: string
                      golongan_darah:
                        type: string
                      no_hp:
                        type: string
                      email:
                        type: string
                      status_hidup:
                        type: string
                      tanggal_meninggal:
                        type: string
                        nullable: true
                      alamat_id:
                        type: integer
                      pendidikan_id:
                        type: integer
                      alamat:
                        type: object
                        properties:
                          id:
                            type: integer
                          label_alamat:
                            type: string
                          is_utama:
                            type: integer
                          alamat_lengkap:
                            type: string
                          jalan:
                            type: string
                          gedung_perumahan:
                            type: string
                          nomor_rumah:
                            type: string
                          blok:
                            type: string
                          no_lantai:
                            type: string
                          no_unit:
                            type: string
                          rt:
                            type: string
                          rw:
                            type: string
                          desa:
                            type: string
                          dusun:
                            type: string
                          kecamatan:
                            type: string
                          kabupaten:
                            type: string
                          provinsi:
                            type: string
                          negara:
                            type: string
                          kode_pos:
                            type: string
                          patokan:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                      pendidikan:
                        type: object
                        properties:
                          id:
                            type: integer
                          tingkat_pendidikan:
                            type: string
                      kk:
                        type: object
                        properties:
                          id:
                            type: integer
                          no_kk:
                            type: string
                          nik_kepala_keluarga:
                            type: string
              example:
                success: true
                message: Success
                data:
                  id: 140
                  nik: '33060242343243545126'
                  nama_lengkap: SITI MUBAIDAH MM
                  kk_id: 23
                  nama_ayah_kandung: SITI CHIPTIYAH MM
                  nama_ibu_kandung: MARGO UTOMO UTOMO
                  jenis_kelamin: Perempuan
                  tanggal_lahir: '1971-01-01T00:00:00.000000Z'
                  tempat_lahir: Purworejo
                  agama: Islam
                  pekerjaan: Petani/Pekebun
                  status_perkawinan: Belum Kawin
                  kewarganegaraan: Indonesia
                  golongan_darah: B
                  no_hp: '081904703153'
                  email: example@example.com
                  status_hidup: HIDUP
                  tanggal_meninggal: null
                  alamat_id: 18
                  pendidikan_id: 5
                  alamat:
                    id: 18
                    label_alamat: Rumah
                    is_utama: 1
                    alamat_lengkap: >-
                      Desa Curug, RT 001 RW 001, Kecamatan Ngombol, Kabupaten
                      Purworejo, Jawa Tengah.
                    jalan: Jln.Lingkar Barat
                    gedung_perumahan: Perum mawar
                    nomor_rumah: '338'
                    blok: '4'
                    no_lantai: '5'
                    no_unit: '6'
                    rt: '2'
                    rw: '2'
                    desa: Curug
                    dusun: Cagar
                    kecamatan: Ngombol
                    kabupaten: Purworejo
                    provinsi: Jawa Tengah
                    negara: Indonesia
                    kode_pos: '54172'
                    patokan: Belakang Puskesmas Ngombol
                    latitude: '-7.7839810'
                    longitude: '109.9614240'
                  pendidikan:
                    id: 5
                    tingkat_pendidikan: SLTA/Sederajat
                  kk:
                    id: 23
                    no_kk: '3306021308080442'
                    nik_kepala_keluarga: '3306020505680007'
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
    put:
      summary: Update by ID
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_penduduk_update_by_id_yml
      description: ''
      tags:
        - Penduduk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      nik:
                        type: string
                      nama_lengkap:
                        type: string
                      kk_id:
                        type: integer
                      nama_ayah_kandung:
                        type: string
                      nama_ibu_kandung:
                        type: string
                      jenis_kelamin:
                        type: string
                      tanggal_lahir:
                        type: string
                      tempat_lahir:
                        type: string
                      agama:
                        type: string
                      pekerjaan:
                        type: string
                      status_perkawinan:
                        type: string
                      kewarganegaraan:
                        type: string
                      golongan_darah:
                        type: string
                      no_hp:
                        type: string
                      email:
                        type: string
                      status_hidup:
                        type: string
                      tanggal_meninggal:
                        type: string
                        nullable: true
                      alamat_id:
                        type: integer
                      pendidikan_id:
                        type: integer
                      alamat:
                        type: object
                        properties:
                          id:
                            type: integer
                          label_alamat:
                            type: string
                          is_utama:
                            type: integer
                          alamat_lengkap:
                            type: string
                          jalan:
                            type: string
                          gedung_perumahan:
                            type: string
                          nomor_rumah:
                            type: string
                          blok:
                            type: string
                          no_lantai:
                            type: string
                          no_unit:
                            type: string
                          rt:
                            type: string
                          rw:
                            type: string
                          desa:
                            type: string
                          dusun:
                            type: string
                          kecamatan:
                            type: string
                          kabupaten:
                            type: string
                          provinsi:
                            type: string
                          negara:
                            type: string
                          kode_pos:
                            type: string
                          patokan:
                            type: string
                          latitude:
                            type: string
                          longitude:
                            type: string
                      pendidikan:
                        type: object
                        properties:
                          id:
                            type: integer
                          tingkat_pendidikan:
                            type: string
                      kk:
                        type: object
                        properties:
                          id:
                            type: integer
                          no_kk:
                            type: string
                          nik_kepala_keluarga:
                            type: string
              example:
                success: true
                message: Data penduduk berhasil diperbarui.
                data:
                  id: 140
                  nik: '33060242343243545126'
                  nama_lengkap: SITI EDITED
                  kk_id: 23
                  nama_ayah_kandung: SITI CHIPTIYAH MM
                  nama_ibu_kandung: MARGO UTOMO UTOMO
                  jenis_kelamin: Perempuan
                  tanggal_lahir: '1971-01-01T00:00:00.000000Z'
                  tempat_lahir: Purworejo
                  agama: Islam
                  pekerjaan: Petani/Pekebun
                  status_perkawinan: Belum Kawin
                  kewarganegaraan: Indonesia
                  golongan_darah: B
                  no_hp: '081904703153'
                  email: example@example.com
                  status_hidup: HIDUP
                  tanggal_meninggal: null
                  alamat_id: 18
                  pendidikan_id: 5
                  alamat:
                    id: 18
                    label_alamat: Rumah
                    is_utama: 1
                    alamat_lengkap: >-
                      Desa Curug, RT 001 RW 001, Kecamatan Ngombol, Kabupaten
                      Purworejo, Jawa Tengah.
                    jalan: Jln.Lingkar Barat
                    gedung_perumahan: Perum mawar
                    nomor_rumah: '338'
                    blok: '4'
                    no_lantai: '5'
                    no_unit: '6'
                    rt: '2'
                    rw: '2'
                    desa: Curug
                    dusun: Cagar
                    kecamatan: Ngombol
                    kabupaten: Purworejo
                    provinsi: Jawa Tengah
                    negara: Indonesia
                    kode_pos: '54172'
                    patokan: Belakang Puskesmas Ngombol
                    latitude: '-7.7839810'
                    longitude: '109.9614240'
                  pendidikan:
                    id: 5
                    tingkat_pendidikan: SLTA/Sederajat
                  kk:
                    id: 23
                    no_kk: '3306021308080442'
                    nik_kepala_keluarga: '3306020505680007'
      parameters:
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/update_by_id'
      servers:
        - url: http://127.0.0.1:8000
  /api/penduduk:
    get:
      summary: Get all, search, pagination
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_penduduk_get_all_search_pagination_yml
      description: ''
      tags:
        - Penduduk
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      data:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                            nik:
                              type: string
                            nama_lengkap:
                              type: string
                            kk_id:
                              type: integer
                            nama_ayah_kandung:
                              type: string
                            nama_ibu_kandung:
                              type: string
                            jenis_kelamin:
                              type: string
                            tanggal_lahir:
                              type: string
                            tempat_lahir:
                              type: string
                            agama:
                              type: string
                            pekerjaan:
                              type: string
                            status_perkawinan:
                              type: string
                              nullable: true
                            kewarganegaraan:
                              type: string
                            golongan_darah:
                              type: string
                              nullable: true
                            no_hp:
                              type: string
                              nullable: true
                            email:
                              type: string
                              nullable: true
                            status_hidup:
                              type: string
                            tanggal_meninggal:
                              type: string
                              nullable: true
                            alamat_id:
                              type: integer
                            pendidikan_id:
                              type: integer
                      first_page_url:
                        type: string
                      from:
                        type: integer
                      last_page:
                        type: integer
                      last_page_url:
                        type: string
                      links:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                              nullable: true
                            label:
                              type: string
                            page:
                              type: string
                              nullable: true
                            active:
                              type: boolean
                      next_page_url:
                        type: string
                      path:
                        type: string
                      per_page:
                        type: integer
                      prev_page_url:
                        type: string
                        nullable: true
                      to:
                        type: integer
                      total:
                        type: integer
              example:
                success: true
                message: Success
                data:
                  current_page: 1
                  data:
                    - id: 4
                      nik: '3306024204110001'
                      nama_lengkap: NAZWA KANAYA ANINDITYA
                      kk_id: 12
                      nama_ayah_kandung: LATIFAH HIDAYATUL NASRUROH
                      nama_ibu_kandung: EKO BUDI PRASETYO
                      jenis_kelamin: Perempuan
                      tanggal_lahir: '2011-04-02T00:00:00.000000Z'
                      tempat_lahir: Purwerejo
                      agama: Islam
                      pekerjaan: Belum/Tidak Bekerja
                      status_perkawinan: null
                      kewarganegaraan: Indonesia
                      golongan_darah: null
                      no_hp: null
                      email: null
                      status_hidup: HIDUP
                      tanggal_meninggal: null
                      alamat_id: 1
                      pendidikan_id: 1
                    - id: 23
                      nik: '3306020809000001'
                      nama_lengkap: ANDI RIZAL MAULANA
                      kk_id: 27
                      nama_ayah_kandung: KUSMIYATI
                      nama_ibu_kandung: SUPARJO
                      jenis_kelamin: Laki-laki
                      tanggal_lahir: '2000-09-08T00:00:00.000000Z'
                      tempat_lahir: Purworejo
                      agama: Islam
                      pekerjaan: Pelajar/Mahasiswa
                      status_perkawinan: null
                      kewarganegaraan: Indonesia
                      golongan_darah: null
                      no_hp: null
                      email: null
                      status_hidup: HIDUP
                      tanggal_meninggal: null
                      alamat_id: 1
                      pendidikan_id: 2
                  first_page_url: http://127.0.0.1:8000/api/penduduk?page=1
                  from: 1
                  last_page: 5
                  last_page_url: http://127.0.0.1:8000/api/penduduk?page=5
                  links:
                    - url: null
                      label: '&laquo; Previous'
                      page: null
                      active: false
                    - url: http://127.0.0.1:8000/api/penduduk?page=1
                      label: '1'
                      page: 1
                      active: true
                    - url: http://127.0.0.1:8000/api/penduduk?page=2
                      label: '2'
                      page: 2
                      active: false
                    - url: http://127.0.0.1:8000/api/penduduk?page=3
                      label: '3'
                      page: 3
                      active: false
                    - url: http://127.0.0.1:8000/api/penduduk?page=4
                      label: '4'
                      page: 4
                      active: false
                    - url: http://127.0.0.1:8000/api/penduduk?page=5
                      label: '5'
                      page: 5
                      active: false
                    - url: http://127.0.0.1:8000/api/penduduk?page=2
                      label: Next &raquo;
                      page: 2
                      active: false
                  next_page_url: http://127.0.0.1:8000/api/penduduk?page=2
                  path: http://127.0.0.1:8000/api/penduduk
                  per_page: 2
                  prev_page_url: null
                  to: 2
                  total: 9
      parameters:
        - name: search
          in: query
          description: ''
          required: true
          schema:
            type: string
          example: '{{keywords}}'
        - name: per_page
          in: query
          description: ''
          required: true
          schema:
            type: string
          example: '{{per_page}}'
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/srt-pengajuan-surat/42/generate:
    get:
      summary: Generate Surat
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_pengajuan_surat_generate_surat_yml
      description: ''
      tags:
        - Pengajuan Surat
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/srt-pengajuan-surat/7/get-auto-values:
    get:
      summary: Get auto values
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_pengajuan_surat_get_auto_values_yml
      description: ''
      tags:
        - Pengajuan Surat
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/srt-pengajuan-surat/38:
    get:
      summary: Get pengajuan surat
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_pengajuan_surat_get_pengajuan_surat_yml
      description: ''
      tags:
        - Pengajuan Surat
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/pengajuan-surat:
    post:
      summary: Mengajukan Surat
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_pengajuan_surat_mengajukan_surat_yml
      description: ''
      tags:
        - Pengajuan Surat
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/mengajukan_surat'
      servers:
        - url: http://127.0.0.1:8000
      x-bruno-variants:
        - summary: Mengajukan Surat
          operationId: >-
            c_agg_projects_kkn_web_desa_bruno_curug_api_doc_generate_surat_steps_mengajukan_surat_yml
          description: ''
          tags:
            - Generate Surat Steps
          responses:
            '200':
              description: ''
          parameters:
            - name: level
              in: query
              description: ''
              required: false
              schema:
                type: string
                enum:
                  - kabupaten
                  - kecamatan
                  - desa
            - name: parent
              in: query
              description: ''
              required: false
              schema:
                type: string
            - name: search
              in: query
              description: ''
              required: false
              schema:
                type: string
            - name: Accept
              in: header
              description: ''
              required: true
              schema:
                type: string
              example: application/json
          requestBody:
            $ref: '#/components/requestBodies/mengajukan_surat_1'
          servers:
            - url: http://127.0.0.1:8000
  /api/wilayah:
    get:
      summary: Get Wilayah
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_wilayah_get_wilayah_yml
      description: ''
      tags:
        - Wilayah
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: true
          schema:
            type: string
            enum:
              - provinsi
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      servers:
        - url: http://127.0.0.1:8000
  /api/ref-profil-desa:
    get:
      summary: Profil Desa
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_profil_desa_profil_desa_yml
      description: ''
      tags:
        - Profil Desa
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/testing:
    get:
      summary: Testing
      operationId: c_agg_projects_kkn_web_desa_bruno_curug_api_doc_testing_testing_yml
      description: ''
      tags:
        - Testing
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/srt-jenis-surat/1:
    get:
      summary: Get Jenis Surat by ID
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_generate_surat_steps_get_jenis_surat_by_id_yml
      description: ''
      tags:
        - Generate Surat Steps
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/srt-jenis-surat:
    get:
      summary: Get All Jenis Surat
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_generate_surat_steps_get_all_jenis_surat_yml
      description: ''
      tags:
        - Generate Surat Steps
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: page
          in: query
          description: ''
          required: true
          schema:
            type: integer
            format: int32
          example: '1'
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      servers:
        - url: http://127.0.0.1:8000
  /api/pengajuan-surat/65:
    post:
      summary: Generate
      operationId: >-
        c_agg_projects_kkn_web_desa_bruno_curug_api_doc_generate_surat_steps_generate_yml
      description: ''
      tags:
        - Generate Surat Steps
      responses:
        '200':
          description: ''
      parameters:
        - name: level
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - kabupaten
              - kecamatan
              - desa
        - name: parent
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: search
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: Accept
          in: header
          description: ''
          required: true
          schema:
            type: string
          example: application/json
      requestBody:
        $ref: '#/components/requestBodies/generate'
      servers:
        - url: http://127.0.0.1:8000
servers: []
components:
  schemas:
    login:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: admin@desa.id
        password: admin123
    create_mastr_field_surat:
      type: object
      properties:
        nama:
          type: string
        label:
          type: string
        source:
          type: string
        source_feld:
          type: string
      example:
        nama: sf
        label: label
        source: source
        source_feld: source_feld
    create_kk:
      type: object
      properties:
        no_kk:
          type: string
        nik_kepala_keluarga:
          type: string
      example:
        no_kk: '23874826745643'
        nik_kepala_keluarga: '2309493827596782'
    create:
      type: object
      properties:
        nik:
          type: string
        nama_lengkap:
          type: string
        kk_id:
          type: integer
        nama_ayah_kandung:
          type: string
        nama_ibu_kandung:
          type: string
        jenis_kelamin:
          type: string
        tanggal_lahir:
          type: string
        tempat_lahir:
          type: string
        agama:
          type: string
        pekerjaan:
          type: string
        status_perkawinan:
          type: string
        kewarganegaraan:
          type: string
        golongan_darah:
          type: string
        no_hp:
          type: string
        email:
          type: string
        status_hidup:
          type: string
        tanggal_meninggal:
          type: string
          nullable: true
        pendidikan_id:
          type: integer
        alamat:
          type: object
          properties:
            label_alamat:
              type: string
            is_utama:
              type: integer
            alamat_lengkap:
              type: string
            jalan:
              type: string
            gedung_perumahan:
              type: string
            nomor_rumah:
              type: integer
            blok:
              type: integer
            no_lantai:
              type: integer
            no_unit:
              type: integer
            rt:
              type: string
            rw:
              type: string
            desa:
              type: string
            dusun:
              type: string
            kecamatan:
              type: string
            kabupaten:
              type: string
            provinsi:
              type: string
            negara:
              type: string
            kode_pos:
              type: string
            patokan:
              type: string
            latitude:
              type: string
            longitude:
              type: string
      example:
        nik: '33060242343243545126'
        nama_lengkap: SITI MUBAIDAH MM
        kk_id: 23
        nama_ayah_kandung: SITI CHIPTIYAH MM
        nama_ibu_kandung: MARGO UTOMO UTOMO
        jenis_kelamin: Perempuan
        tanggal_lahir: '1971-01-01T00:00:00.000000Z'
        tempat_lahir: Purworejo
        agama: Islam
        pekerjaan: Petani/Pekebun
        status_perkawinan: Belum Kawin
        kewarganegaraan: Indonesia
        golongan_darah: B
        no_hp: '081904703153'
        email: example@example.com
        status_hidup: HIDUP
        tanggal_meninggal: null
        pendidikan_id: 5
        alamat:
          label_alamat: Rumah
          is_utama: 1
          alamat_lengkap: >-
            Desa Curug, RT 001 RW 001, Kecamatan Ngombol, Kabupaten Purworejo,
            Jawa Tengah.
          jalan: Jln.Lingkar Barat
          gedung_perumahan: Perum mawar
          nomor_rumah: 338
          blok: 4
          no_lantai: 5
          no_unit: 6
          rt: '2'
          rw: '2'
          desa: Curug
          dusun: Cagar
          kecamatan: Ngombol
          kabupaten: Purworejo
          provinsi: Jawa Tengah
          negara: Indonesia
          kode_pos: '54172'
          patokan: Belakang Puskesmas Ngombol
          latitude: '-7.7839810'
          longitude: '109.9614240'
    update_by_id:
      type: object
      properties:
        nik:
          type: string
        nama_lengkap:
          type: string
        kk_id:
          type: integer
        nama_ayah_kandung:
          type: string
        nama_ibu_kandung:
          type: string
        jenis_kelamin:
          type: string
        tanggal_lahir:
          type: string
        tempat_lahir:
          type: string
        agama:
          type: string
        pekerjaan:
          type: string
        status_perkawinan:
          type: string
        kewarganegaraan:
          type: string
        golongan_darah:
          type: string
        no_hp:
          type: string
        email:
          type: string
        status_hidup:
          type: string
        tanggal_meninggal:
          type: string
          nullable: true
        pendidikan_id:
          type: integer
        alamat:
          type: object
          properties:
            label_alamat:
              type: string
            is_utama:
              type: integer
            alamat_lengkap:
              type: string
            jalan:
              type: string
            gedung_perumahan:
              type: string
            nomor_rumah:
              type: integer
            blok:
              type: integer
            no_lantai:
              type: integer
            no_unit:
              type: integer
            rt:
              type: string
            rw:
              type: string
            desa:
              type: string
            dusun:
              type: string
            kecamatan:
              type: string
            kabupaten:
              type: string
            provinsi:
              type: string
            negara:
              type: string
            kode_pos:
              type: string
            patokan:
              type: string
            latitude:
              type: string
            longitude:
              type: string
      example:
        nik: '33060242343243545126'
        nama_lengkap: SITI EDITED
        kk_id: 23
        nama_ayah_kandung: SITI CHIPTIYAH MM
        nama_ibu_kandung: MARGO UTOMO UTOMO
        jenis_kelamin: Perempuan
        tanggal_lahir: '1971-01-01T00:00:00.000000Z'
        tempat_lahir: Purworejo
        agama: Islam
        pekerjaan: Petani/Pekebun
        status_perkawinan: Belum Kawin
        kewarganegaraan: Indonesia
        golongan_darah: B
        no_hp: '081904703153'
        email: example@example.com
        status_hidup: HIDUP
        tanggal_meninggal: null
        pendidikan_id: 5
        alamat:
          label_alamat: Rumah
          is_utama: 1
          alamat_lengkap: >-
            Desa Curug, RT 001 RW 001, Kecamatan Ngombol, Kabupaten Purworejo,
            Jawa Tengah.
          jalan: Jln.Lingkar Barat
          gedung_perumahan: Perum mawar
          nomor_rumah: 338
          blok: 4
          no_lantai: 5
          no_unit: 6
          rt: '2'
          rw: '2'
          desa: Curug
          dusun: Cagar
          kecamatan: Ngombol
          kabupaten: Purworejo
          provinsi: Jawa Tengah
          negara: Indonesia
          kode_pos: '54172'
          patokan: Belakang Puskesmas Ngombol
          latitude: '-7.7839810'
          longitude: '109.9614240'
    mengajukan_surat:
      type: object
      properties:
        jenis_surat_id:
          type: integer
        niks:
          type: array
          items:
            type: string
        keperluan:
          type: string
          nullable: true
      example:
        jenis_surat_id: 1
        niks:
          - '3306024101710005'
          - '3306024102800001'
        keperluan: null
    mengajukan_surat_1:
      type: object
      properties:
        jenis_surat_id:
          type: integer
        niks:
          type: array
          items:
            type: string
        keperluan:
          type: string
          nullable: true
      example:
        jenis_surat_id: 1
        niks:
          - '3306025404160002'
          - '3306024911510002'
        keperluan: null
    generate:
      type: object
      properties: {}
  requestBodies:
    login:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/login'
      description: ''
      required: true
    create_mastr_field_surat:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_mastr_field_surat'
      description: ''
      required: true
    create_kk:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_kk'
      description: ''
      required: true
    create:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create'
      description: ''
      required: true
    update_by_id:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/update_by_id'
      description: ''
      required: true
    mengajukan_surat:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/mengajukan_surat'
      description: ''
      required: true
    mengajukan_surat_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/mengajukan_surat_1'
      description: ''
      required: true
    generate:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/generate'
      description: ''
      required: true
  securitySchemes: {}
